data:
  target: main.DataModuleFromConfig
  params:
    num_workers: 0
    batch_size: 5
    train:
      target: rdm.data.base.QueryDataset
      params:
        k: 4
        dset_config:
          target: rdm.data.imagenet.ImageNetTrainFaceBlurred
          params:
            config:
              size: 256
    validation:
      target: rdm.data.base.QueryDataset
      params:
        k: 4
        dset_config:
          target: rdm.data.imagenet.ImageNetValidationFaceBlurred
          params:
            config:
              size: 256
