data:
  target: main.DataModuleFromConfig
  params:
    num_workers: 0
    batch_size: 5
    train:
      target: rdm.data.base.QueryDataset
      params:
        k: 20
        dset_config:
          target: rdm.data.mscoco.MSCOCO
          params:
            root: /datasets01/COCO/060817/train2014/
            annFile: /datasets01/COCO/060817/annotations/captions_train2014.json
            size: 256
    validation:
      target: rdm.data.base.QueryDataset
      params:
        k: 20
        dset_config:
          target: rdm.data.mscoco.MSCOCO
          params:
            root: /datasets01/COCO/060817/val2014/
            annFile: /datasets01/COCO/060817/annotations/captions_val2014.json
            size: 256
    